### ISSUE TITLE
Feature Request: Cloning & sourceNamespace

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/netapp-astra-toolkits#10]
Hi,

currently, Astra Control manages Apps through namespaces or labels.
That implies that cloning an app can be done on a subset or resources belonging to a namespace.
However, at the destination, Astra Control will always create a new namespace to create the objects.

The cloning operation of the toolkit refers to **sourceNamespace**, when it should actually refer to **sourceAppId** in order to bring the toolkit user closer to what can be achieved in the GUI or through API. The value of the field is correct, it's more a labeling coherency.

```
(toolkit) bash-5.1# ./toolkit.py clone -h
usage: toolkit.py clone [-h]
                        [--sourceNamespace {97bc7669-baac-44d6-b89a-614af5a75e8d,64e4bd22-f88f-472d-9562-68aa1743ac75,f6c8f359-a834-4f5a-9e56-279fb87d9c34,b535e36e-c442-4de7-bda1-ca3807ab81b6}]
                        [--backupID {31cce752-668d-40a5-bf10-cd05150b2fc9,6db519fd-5256-463f-b36e-32eb8895a130}]
                        [--clusterID {c03c9984-e46d-42b0-ae3f-89c8deb08cd0,134f0bcf-902d-4746-92d6-6a82a52d9db7}] [--destName DESTNAME]
                        [--destNamespace DESTNAMESPACE]

optional arguments:
  -h, --help            show this help message and exit
  --sourceNamespace {97bc7669-baac-44d6-b89a-614af5a75e8d,64e4bd22-f88f-472d-9562-68aa1743ac75,f6c8f359-a834-4f5a-9e56-279fb87d9c34,b535e36e-c442-4de7-bda1-ca3807ab81b6}
                        Source namespace to clone
  --backupID {31cce752-668d-40a5-bf10-cd05150b2fc9,6db519fd-5256-463f-b36e-32eb8895a130}
                        Source backup to clone
  --clusterID {c03c9984-e46d-42b0-ae3f-89c8deb08cd0,134f0bcf-902d-4746-92d6-6a82a52d9db7}
                        Cluster to clone to
  --destName DESTNAME   clone name
  --destNamespace DESTNAMESPACE
                        Destination namespace
```

Test done with jpaetzel0614/k8scloudcontrol:1.2

**Comment by MichaelHaigh** [comment]
Hey [YvosOnTheHub](https://github.com/YvosOnTheHub), thanks for opening this issue.  With the most recent Astra Control release that just went out and the modification of how apps are managed, I took the liberty to modify how the toolkit cloning works.  Please check out the [docs here](https://github.com/NetApp/netapp-astra-toolkits/tree/main/docs/toolkit/clone#clone) and let me know if you have any feedback.  But I think this issue can be closed as completed.
