### ISSUE TITLE
[Feature addition] Add in-app restore functionality in SDK

### ISSUE THREAD

**Issue by kulkarnn** [NetApp/netapp-astra-toolkits#6]
The restore functionality in the new co-dev release is something we intend to use for our CI/CD use-case examples. It would be helpful to have this feature in SDK so we can continue to use the SDK for our scripts and pipeline examples.

**Comment by jpaetzel** [comment]
f5d361000dc67e735fb99b439a453ea5ad13d6db added restoreApp to the SDK and
25e5b4c8c2e5914d1b2ff8f7e383f34c1c6a4610 wired up toolkit.py to use it.
