### ISSUE TITLE
Feature Request: Differentiate "Unmanaged" & "Ignored" objects

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/netapp-astra-toolkits#7]
Hi
several objects (apps for instance) are categorized in 3 different flavors:
- managed
- discovered & unmanaged
- discovered & ignored

"./toolkit.py list app" lists _managed apps_
while
"./toolkit.py list app **-u**" lists _unmanaged apps_

The toolkit does not differentiate **unmanaged** from **ignored**, which can lead to long lists of uuid or names that you dont want to see.

Proposition:
"./toolkit.py list app" lists managed apps
"./toolkit.py list app **-u**" lists discovered & unmanaged apps
"./toolkit.py list app **-i**" lists discovered & ignored apps

Test done with jpaetzel0614/k8scloudcontrol:1.2

**Comment by jpaetzel** [comment]
836e483 implements this.  Thanks for making this suggestion.
