### ISSUE TITLE
Feature Request: Make the help outputs more human readable

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/netapp-astra-toolkits#9]
Hi
the toolkit provides a very useful output when adding the flag **-h**, as it will provide all the possible UUID you can set.
However, in a large environment, the ouput can quickly fill up the screen with UUID, making the ouput unusable.

A proposition to improve this (example with the _manage app -h_ command)
- toolkit.py manage app -h: displays all the flags, but not the possible values
- toolkit.py manage app -hh: displays all the flags, with the possible values

Also, a UUID is not human friendly, maybe use AppName/Namespace instead, which then will simplify the process ?

Test done with jpaetzel0614/k8scloudcontrol:1.2

**Comment by MichaelHaigh** [comment]
Hey [YvosOnTheHub](https://github.com/YvosOnTheHub), thanks for opening up this issue.  I've recently implemented a new top-level "--fast" option which should resolve this issue.  It works by not populating the choices list, resulting in the simplified (and faster) help text you're asking for.

For more info, please see the [docs here](https://github.com/NetApp/netapp-astra-toolkits/tree/main/docs/toolkit/optionalargs#fast).  I'll leave this issue open for a little bit in case you have any feedback, but then will close it as completed.

FYI the secondary ask about not using the UUID is on my to-do list, but is a larger feature so it will take some time.
